server:
  port: 8802
spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
      bindings:
        intput:
          destination: studyExchange
          content-type: application/json
          binder: defaultRabbit
  rabbitmq:
    host: 192.168.150.128
    port: 5672
    username: fufu
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5
    instance-id: receive-8802.com
    prefer-ip-address: true